### ISSUE TITLE
Add meta tags to your index for increased seo goodness

### ISSUE THREAD

**Issue by MichaelNeas** [Jdcorley/Resume-Web-Page#3]
:)

**Comment by Jdcorley** [comment]
#1

**Comment by Jdcorley** [comment]
https://github.com/Jdcorley/Resume-Web-Page/commit/beda6066abb4525b65bd17735a9343dd8053707f

was it just this or are there more I should add?

**Comment by MichaelNeas** [comment]
`	

    <meta charset="utf-8">
	<meta name='keywords' content=''>
	<meta name='description' content='A personal website to show a little about me =)'>
	<meta name='author' content=''>
	<meta name='owner' content=''>
	<meta name='url' content=''>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
`

**Comment by MichaelNeas** [comment]
@Jdcorley  these are a few! you can also add in robots https://yoast.com/robots-meta-tags/

**Comment by MichaelNeas** [comment]
good looks
